# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('fgdzc', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=50)),
                ('fdate', models.DateTimeField()),
                ('fuser', models.CharField(max_length=50)),
                ('fdep', models.CharField(max_length=50)),
                ('fip', models.GenericIPAddressField()),
                ('fdate_rz', models.DateField()),
                ('fdate_bf', models.DateField()),
                ('smark', models.BooleanField()),
                ('fstore', models.CharField(max_length=50)),
                ('fuserold', models.CharField(max_length=50)),
                ('f1', models.CharField(max_length=30)),
                ('f2', models.CharField(max_length=30)),
                ('fdate_ys', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='fstate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itassets.State'),
        ),
    ]
